complete -c lazygit -f -a 'status branch log stash' -d 'Git view to open'
complete -c lazygit -f -n '__fish_seen_subcommand_from completion' -a 'bash fish zsh powershell' -d 'Shell to generate completion for'
complete -c lazygit -s h -l help -d 'Show help'
complete -c lazygit -s p -l path -r -F -d 'Path to the repository'
complete -c lazygit -s f -l filter -r -d 'Filter repositories'
complete -c lazygit -s v -l version -d 'Show version'
complete -c lazygit -s d -l debug -d 'Enable debug logging'
complete -c lazygit -s l -l logs -d 'Show log panel'
complete -c lazygit -l profile -d 'Enable profiling'
complete -c lazygit -s c -l config -r -F -d 'Use a config file'
complete -c lazygit -l print-config-dir -d 'Print config directory'
complete -c lazygit -l use-config-dir -d 'Use config directory'
complete -c lazygit -s w -l work-tree -r -F -d 'Git work tree'
complete -c lazygit -s g -l git-dir -r -F -d 'Git directory'
complete -c lazygit -l use-config-file -d 'Use config file'
complete -c lazygit -l screen-mode -r -a 'normal half-full' -d 'Screen mode'
