complete -c pwsh -l Login -d 'Start a login shell'
complete -c pwsh -l NoLogo -d 'Hide the startup banner'
complete -c pwsh -l NoExit -d 'Do not exit after running startup commands'
complete -c pwsh -l NoProfile -d 'Do not load the profile'
complete -c pwsh -l NonInteractive -d 'Do not present an interactive prompt'
complete -c pwsh -l File -r -F -d 'Run a PowerShell script file'
complete -c pwsh -l Command -r -d 'Run the specified commands'
complete -c pwsh -l EncodedCommand -r -d 'Run a Base64-encoded command'
complete -c pwsh -l WorkingDirectory -r -a '(__fish_complete_directories)' -d 'Set the working directory'
complete -c pwsh -l ConfigurationName -r -d 'Specify a session configuration'
complete -c pwsh -l Version -r -d 'Start the specified PowerShell version'
complete -c pwsh -l Help -d 'Show help'
