complete -c stylua -s a -l allow-hidden -d 'Format hidden files'
complete -c stylua -s c -l check -d 'Check formatting without writing'
complete -c stylua -l color -r -a 'always ansi auto never' -d 'Color output'
complete -c stylua -s f -l config-path -r -F -d 'Path to configuration file'
complete -c stylua -s g -l glob -r -d 'Glob pattern for files'
complete -c stylua -l lsp -d 'Run as a language server'
complete -c stylua -l no-editorconfig -d 'Ignore EditorConfig files'
complete -c stylua -l no-ignore-vcs -d 'Ignore VCS ignore files'
complete -c stylua -l num-threads -r -d 'Number of threads'
complete -c stylua -l output-format -r -a 'standard summary json' -d 'Output format'
complete -c stylua -l range-start -r -d 'Start byte offset'
complete -c stylua -l range-end -r -d 'End byte offset'
complete -c stylua -l respect-ignores -d 'Respect ignore files'
complete -c stylua -s s -l search-parent-directories -d 'Search parent directories for config'
complete -c stylua -l stdin-filepath -r -F -d 'Path of stdin input'
complete -c stylua -s v -l verbose -d 'Verbose output'
complete -c stylua -s V -l version -d 'Show version'
complete -c stylua -l verify -d 'Verify formatted output'
complete -c stylua -l call-parentheses -r -a 'Always NoSingle String' -d 'Function call parentheses'
complete -c stylua -l column-width -r -d 'Column width'
complete -c stylua -l indent-type -r -a 'Tabs Spaces' -d 'Indentation type'
complete -c stylua -l indent-width -r -d 'Indentation width'
complete -c stylua -l line-endings -r -a 'Unix Windows WindowsOld Auto' -d 'Line ending style'
complete -c stylua -l quote-style -r -a 'Auto ForceSingle ForceDouble' -d 'Quote style'
complete -c stylua -l sort-requires -d 'Sort require statements'
complete -c stylua -l syntax -r -a 'All Lua51 Lua52 Lua53 Lua54 Luau' -d 'Lua syntax version'
