--- Keymaps Configuration.
--- Sets up global, leader, and plugin-specific keybindings.
--- @module "config.keymaps"

local map = vim.keymap.set
-- Special {{{
-- Package JSON Check
local pj = require("plugins.QDtb.package_json")
map("n", "<leader>z", pj.check_npm_project, { desc = "Check if NPM project." })
-- Focus & Leap
require("focus").setup()
map({ "n", "x", "o" }, "S", "<plug>(leap-backward)")
map({ "n", "x", "o" }, "gs", "<plug>(leap-from-window)")
map({ "n", "x", "o" }, "gS", "<plug>(leap)")
-- }}}
-- User Leader Mappings {{{
map("n", "<leader>a", "<cmd>silent !npx prettier --write % &<CR>", { silent = true })
map("n", "<leader>B", "<cmd>Telescope buffers<CR>", { silent = true })
map("n", "<leader>C", "<cmd>Telescope help_tags<CR>", { silent = true })
map("n", "<leader>c", "<cmd>lua MiniPick.builtin.cli()<CR>")
map("n", "<leader>D", "<cmd>Telescope colorscheme<CR>", { silent = true })
map("n", "<leader>d", "<cmd>lua MiniPick.builtin.grep_live()<CR>")
map("n", "<leader>E", "<cmd>lua MiniPick.builtin.files()<CR>")
map("n", "<leader>e", "<cmd>lua MiniPick.builtin.grep()<CR>")
map("n", "<leader>F", "<cmd>restart<cr>")
map("n", "<leader>f", "<cmd><up><cr>")
map("n", "<leader>g", "<cmd>set wrap<cr><cmd>Goyo<cr>")
map("n", "<leader>H", "<cmd>lua MiniPick.builtin.help()<CR>", { desc = "MiniPick Help" })
map("n", "<leader>h", "<cmd>set nowrap<cr>:Goyo<cr>", { silent = true })
map("n", "<leader>i", "<cmd>Limelight!!<cr>", { silent = true })
map("n", "<leader>J", ":<c-p><cr>")
map("n", "<leader>j", ":<c-p>")
map("n", "<leader>K", "/<c-f>")
map("n", "<leader>k", "/<up>")
map("n", "<leader>l", "<cmd>cw<cr>")
map("n", "<leader>m", "=ip")
map("n", "<leader>n", "<cmd>NERDTree<cr>", { silent = true })
map("n", "<leader>o", "<cmd>cd %:p:h<CR>", { silent = true })
map("n", "<leader>p", "<cmd>lua MiniExtra.pickers.colorschemes()<CR>")
map("n", "<leader>R", "qr", { desc = "Record Macro to 'r'" })
map("n", "<leader>r", "q")
map("n", "<leader>s", ":%s//<left>")
map("n", "<leader>t", '<cmd>lua MiniSessions.read("0")<CR>')
map("n", "<leader>u", "<cmd>lua MiniPick.builtin.buffers()<CR>")
map("n", "<leader>v", "<cmd>TZNarrow<CR>")
map("n", "<leader>w", require("plugins.QDtb.lua_format").format, { desc = "Run Formatting" })
map("n", "<leader>x", "<cmd>Telescope find_files<CR>", { silent = true })
map("n", "<leader>y", "<cmd>Telescope live_grep<CR>", { silent = true })
-- }}}
-- User General & Mode Mappings {{{
-- Stable
map("n", "<CR>", "yyp")
map("n", "<S-CR>", "dd O")
map("i", "<S-CR>", "<ESC>dd O")
map("i", "<C-CR>", "<ESC>}i")
map("n", "<C-CR>", "}i")
map("i", "<C-S-CR>", "<ESC>{i")
map("n", "<C-S-CR>", "{i")
map("n", "<BS>", "<LEFT><DEL>")
map("v", "<BS>", "x")
map("n", "<S-BS>", "<C-i>")
map("i", "<A-BS>", "<ESC>dd O")
map("n", "<A-BS>", "dd O")
map("i", "<C-BS>", "<ESC><RIGHT>dbi")
map("n", "<C-BS>", "db")
vim.keymap.set("n", "<c-l>", "J")
vim.keymap.set({ "i", "v" }, "<c-l>", "<c-o>J")
-- map("n", "/", "<cmd>lua MiniPick.builtin.files()<CR>")
vim.keymap.set("n", "/", "<cmd>Telescope find_files<CR>")
vim.keymap.set("n", "A", "v")
vim.keymap.set("n", "a", "V")
vim.keymap.set("n", "b", "mA")
vim.keymap.set("n", "ds", "d/")
map("n", "E", "<cmd>cd %:p:h<CR>")
vim.keymap.set("n", "e", ":Startify<CR>", { silent = true })
-- vim.keymap.set("n", "f", "z")
vim.keymap.set("n", "fd", "zd")
vim.keymap.set("n", "fE", "zE")
vim.keymap.set("n", "ff", "zz")
vim.keymap.set("n", "fj", "zt")
vim.keymap.set("n", "fk", "zk")
vim.keymap.set("n", "fm", "zm")
vim.keymap.set("n", "fM", "zM")
vim.keymap.set("n", "fo", "zo")
vim.keymap.set("n", "fO", "zO")
vim.keymap.set("n", "fr", "zr")
vim.keymap.set("n", "fR", "zR")
vim.keymap.set("n", "ft", "zf")
vim.keymap.set("n", "[f", "[z")
vim.keymap.set("n", "]f", "]z")
-- Fold method: marker / marker + close all / revert to treesitter or indent
local fold_this = require("plugins.fold_this.fold_this")
map("n", "zq", function()
	fold_this.set_marker(false)
end, { desc = "Fold: marker method" })
map("n", "zQ", function()
	fold_this.set_marker(true)
end, { desc = "Fold: marker method, close all" })
map("n", "zY", function()
	local win = vim.api.nvim_get_current_win()
	vim.w[win].fold_this_marker = nil
	fold_this.apply_default(win, vim.api.nvim_get_current_buf())
end, { desc = "Fold: revert to treesitter/indent" })
vim.keymap.set("n", "G", "Gzm")
map("n", "gg", "ggzM")
vim.keymap.set("n", "I", "a")
vim.keymap.set("n", "L", "l")
vim.keymap.set("n", "l", "f")
vim.keymap.set({ "n", "v" }, "M", "zM{zozz")
vim.keymap.set("n", "m", "F")
vim.keymap.set("v", "m", "F")
vim.keymap.set("n", "Q", ":qa<cr>")
vim.keymap.set("n", "q", ":q<cr>")
map("n", "R", "q")
vim.keymap.set("n", "r", "/")
vim.keymap.set({ "n", "x", "o" }, "s", "<Plug>(leap)")
map("n", "X", "x")
vim.keymap.set("n", "t", "'Azo")
map("n", "U", "<cmd>cd %:p:h<CR>")
map("n", "V", "A")
vim.keymap.set("n", "v", "Vc")
vim.keymap.set("v", "v", "<ESC>Vc")
vim.keymap.set("n", "w", "<c-w>")
-- vim.keymap.set("n", "x", "<c-i>")
-- vim.keymap.set("n", "z", "<c-o>")
vim.keymap.set("n", ",", "h")
vim.keymap.set({ "n", "v" }, "`", "~")
map({ "i", "x", "n", "s" }, "<C-s>", "<cmd>w<cr><esc>", { desc = "Save File" })
-- Undo/Redo
map("n", "<c-z>", "u")
map({ "i", "v" }, "<c-z>", "<c-o>u")
-- MiniFiles
map("n", "-", function()
	require("mini.files").open()
end, { noremap = true, silent = true, desc = "Open MiniFiles" })
map("n", "h", function()
	require("mini.files").open(vim.api.nvim_buf_get_name(0))
end, { noremap = true, silent = true, desc = "Open MiniFiles" })
-- Mouse / Misc Control Maps
map("n", "<X2Mouse>", "<c-i>")
map("n", "<X1Mouse>", "<c-o>")
map("n", "<c-a>", "|")
map("i", "<c-a>", "<ESC>|i")
map("i", "<c-b>", "<LEFT>")
map("i", "<c-e>", "<ESC>A")
map("i", "<c-f>", "<RIGHT>")
map("i", "<c-d>", "<DEL>")
-- }}}
-- LazyVim Default Mappings {{{
-- Better up/down
map({ "n", "x" }, "j", "v:count == 0 ? 'gj' : 'j'", { desc = "Down", expr = true, silent = true })
map({ "n", "x" }, "<Down>", "v:count == 0 ? 'gj' : 'j'", { desc = "Down", expr = true, silent = true })
map({ "n", "x" }, "k", "v:count == 0 ? 'gk' : 'k'", { desc = "Up", expr = true, silent = true })
map({ "n", "x" }, "<Up>", "v:count == 0 ? 'gk' : 'k'", { desc = "Up", expr = true, silent = true })
-- Move to window using the <ctrl> hjkl keys
map("n", "<C-h>", "<C-w>h", { desc = "Go to Left Window", remap = true })
map("n", "<C-j>", "<C-w>j", { desc = "Go to Lower Window", remap = true })
map("n", "<C-k>", "<C-w>k", { desc = "Go to Upper Window", remap = true })
map("n", "<C-l>", "<C-w>l", { desc = "Go to Right Window", remap = true })
-- Resize window using <ctrl> arrow keys
map("n", "<C-Up>", "<cmd>resize +2<cr>", { desc = "Increase Window Height" })
map("n", "<C-Down>", "<cmd>resize -2<cr>", { desc = "Decrease Window Height" })
map("n", "<C-Left>", "<cmd>vertical resize -2<cr>", { desc = "Decrease Window Width" })
map("n", "<C-Right>", "<cmd>vertical resize +2<cr>", { desc = "Increase Window Width" })
-- Move Lines
map("n", "<A-j>", "<cmd>execute 'move .+' . v:count1<cr>==", { desc = "Move Down" })
map("n", "<A-k>", "<cmd>execute 'move .-' . (v:count1 + 1)<cr>==", { desc = "Move Up" })
map("i", "<A-j>", "<esc><cmd>m .+1<cr>==gi", { desc = "Move Down" })
map("i", "<A-k>", "<esc><cmd>m .-2<cr>==gi", { desc = "Move Up" })
map("v", "<A-j>", ":<C-u>execute \"'<,'>move '>+\" . v:count1<cr>gv=gv", { desc = "Move Down" })
map("v", "<A-k>", ":<C-u>execute \"'<,'>move '<-\" . (v:count1 + 1)<cr>gv=gv", { desc = "Move Up" })
-- Buffers
map("n", "<S-h>", "<cmd>bprevious<cr>", { desc = "Prev Buffer" })
map("n", "<S-l>", "<cmd>bnext<cr>", { desc = "Next Buffer" })
map("n", "[b", "<cmd>bprevious<cr>", { desc = "Prev Buffer" })
map("n", "]b", "<cmd>bnext<cr>", { desc = "Next Buffer" })
map("n", "<leader>bb", "<cmd>e #<cr>", { desc = "Switch to Other Buffer" })
map("n", "<leader>`", "<cmd>e #<cr>", { desc = "Switch to Other Buffer" })
map("n", "<leader>bD", "<cmd>:bd<cr>", { desc = "Delete Buffer and Window" })
-- Clear search on escape
map({ "i", "n", "s" }, "<esc>", "<cmd>noh<cr><esc>", { desc = "Escape and Clear hlsearch" })
-- Clear search, diff update and redraw
map(
	"n",
	"<leader>ur",
	"<Cmd>nohlsearch<Bar>diffupdate<Bar>normal! <C-L><CR>",
	{ desc = "Redraw / Clear hlsearch / Diff Update" }
)
-- Saner behavior of n and N
map("n", "n", "'Nn'[v:searchforward].'zv'", { expr = true, desc = "Next Search Result" })
map("x", "n", "'Nn'[v:searchforward]", { expr = true, desc = "Next Search Result" })
map("o", "n", "'Nn'[v:searchforward]", { expr = true, desc = "Next Search Result" })
map("n", "N", "'nN'[v:searchforward].'zv'", { expr = true, desc = "Prev Search Result" })
map("x", "N", "'nN'[v:searchforward]", { expr = true, desc = "Prev Search Result" })
map("o", "N", "'nN'[v:searchforward]", { expr = true, desc = "Prev Search Result" })
-- Add undo break-points
map("i", ",", ",<c-g>u")
map("i", ".", ".<c-g>u")
map("i", ";", ";<c-g>u")
-- Better indenting
map("x", "<", "<gv")
map("x", ">", ">gv")
-- Commenting
map("n", "gco", "o<esc>Vcx<esc><cmd>normal gcc<cr>fxa<bs>", { desc = "Add Comment Below" })
map("n", "gcO", "O<esc>Vcx<esc><cmd>normal gcc<cr>fxa<bs>", { desc = "Add Comment Above" })
-- New file
map("n", "<leader>fn", "<cmd>enew<cr>", { desc = "New File" })
-- Location and Quickfix lists
map("n", "<leader>xl", function()
	local success, err = pcall(function()
		if vim.fn.getloclist(0, { winid = 0 }).winid ~= 0 then
			vim.cmd.lclose()
		else
			vim.cmd.lopen()
		end
	end)
	if not success and err then
		vim.notify(err, vim.log.levels.ERROR)
	end
end, { desc = "Location List" })
map("n", "<leader>xq", function()
	local success, err = pcall(function()
		if vim.fn.getqflist({ winid = 0 }).winid ~= 0 then
			vim.cmd.cclose()
		else
			vim.cmd.copen()
		end
	end)
	if not success and err then
		vim.notify(err, vim.log.levels.ERROR)
	end
end, { desc = "Quickfix List" })
map("n", "[q", vim.cmd.cprev, { desc = "Previous Quickfix" })
map("n", "]q", vim.cmd.cnext, { desc = "Next Quickfix" })
-- Diagnostics
local diagnostic_goto = function(next, severity)
	return function()
		vim.diagnostic.jump({
			count = (next and 1 or -1) * vim.v.count1,
			severity = severity and vim.diagnostic.severity[severity] or nil,
			float = true,
		})
	end
end
map("n", "<leader>cd", vim.diagnostic.open_float, { desc = "Line Diagnostics" })
map("n", "]d", diagnostic_goto(true), { desc = "Next Diagnostic" })
map("n", "[d", diagnostic_goto(false), { desc = "Prev Diagnostic" })
map("n", "]e", diagnostic_goto(true, "ERROR"), { desc = "Next Error" })
map("n", "[e", diagnostic_goto(false, "ERROR"), { desc = "Prev Error" })
map("n", "]w", diagnostic_goto(true, "WARN"), { desc = "Next Warning" })
map("n", "[w", diagnostic_goto(false, "WARN"), { desc = "Prev Warning" })
-- Utilities
map("n", "<leader>qq", "<cmd>qa<cr>", { desc = "Quit All" })
map("n", "<leader>ui", vim.show_pos, { desc = "Inspect Pos" })
map("n", "<leader>uI", function()
	vim.treesitter.inspect_tree()
	vim.api.nvim_input("I")
end, { desc = "Inspect Tree" })
-- Windows & Tabs
map("n", "<leader>-", "<C-W>s", { desc = "Split Window Below", remap = true })
map("n", "<leader>|", "<C-W>v", { desc = "Split Window Right", remap = true })
map("n", "<leader>wd", "<C-W>c", { desc = "Delete Window", remap = true })
map("n", "<leader><tab>l", "<cmd>tablast<cr>", { desc = "Last Tab" })
map("n", "<leader><tab>o", "<cmd>tabonly<cr>", { desc = "Close Other Tabs" })
map("n", "<leader><tab>f", "<cmd>tabfirst<cr>", { desc = "First Tab" })
map("n", "<leader><tab><tab>", "<cmd>tabnew<cr>", { desc = "New Tab" })
map("n", "<leader><tab>]", "<cmd>tabnext<cr>", { desc = "Next Tab" })
map("n", "<leader><tab>d", "<cmd>tabclose<cr>", { desc = "Close Tab" })
map("n", "<leader><tab>[", "<cmd>tabprevious<cr>", { desc = "Previous Tab" })
-- }}}
-- Footer
-- vim:foldmethod=marker:foldlevel=1

-- -- vim.keymap.set('i', 'kj', '<ESC>')
-- -- vim.keymap.set('i', 'jk', '<ESC>')
-- vim.keymap.set("n", "<S-CR>", "yyP")
-- vim.keymap.set("n", "<S-CR>", "yyP")
-- vim.keymap.set("v", "<S-CR>", "yP")
-- vim.keymap.set("n", "<CR>", "yyp")
-- vim.keymap.set("v", "<CR>", "yp")
-- vim.keymap.set("n", "/", "<cmd>lua MiniPick.builtin.files()<CR>")
-- vim.keymap.set("n", ",", "}")
-- vim.keymap.set("n", "a", "V")
-- vim.keymap.set("n", "E", "<cmd>cd %:p:h<CR>")
-- vim.keymap.set("n", "e", "<cmd>Startify<CR>")
-- vim.keymap.set("n", "gg", "ggzM")
-- vim.keymap.set("n", "I", "a")
-- -- vim.keymap.set'n', 'J', '')
-- -- vim.keymap.set('n', 'K', '')
-- -- vim.keymap.set('n', 'Q', '<cmd>lua MiniSessions.write(0)<CR>')
-- -- require('mini.splitjoin').setup({ mappings = { toggle = 'm' } })
-- -- vim.keymap.set('n', 'q', '<cmd>q<CR>')
-- vim.keymap.set("n", "R", "q")
-- vim.keymap.set("n", "r", "/")
-- -- vim.keymap.set('n', 'T', 'A<c-r>+<ESC>')
-- -- vim.keymap.set('n', 'T', '')
-- -- vim.keymap.set('n', 't', '@r')
-- -- vim.keymap.set('n', 't', '<cmd>bd<CR>')
-- vim.keymap.set("n", "U", "<cmd>cd %:p:h<CR>")
-- vim.keymap.set("n", "V", "A")
-- vim.keymap.set("n", "X", "x")
-- vim.keymap.set("n", ";", ";")
-- -- vim.keymap.set('n', ';', 'q:')
-- vim.keymap.set("n", "-", function()
-- 	require("mini.files").open()
-- end, { noremap = true, silent = true, desc = "Open MiniFiles" })
-- -- vim.keymap.set('n', 'E', function()
-- -- 	local directory = '~/Source/Repos/be-gccpilot03-py/frontend'
-- -- 	vim.cmd('silent! Explore ' .. vim.fn.escape(directory, ' '))
-- -- 	vim.cmd('cd ' .. vim.fn.escape(directory, ' '))
-- -- end)
-- vim.keymap.set("n", "h", function()
-- 	MiniFiles.open(vim.api.nvim_buf_get_name(0))
-- end, { noremap = true, silent = true, desc = "Open MiniFiles" })
-- vim.keymap.set("n", "<X2Mouse>", "<c-i>")
-- vim.keymap.set("n", "<X1Mouse>", "<c-o>")
-- vim.keymap.set("n", "<c-a>", "|")
-- vim.keymap.set("i", "<c-a>", "<ESC>|i")
-- vim.keymap.set("i", "<c-b>", "<LEFT>")
-- vim.keymap.set("i", "<c-e>", "<ESC>A")
-- vim.keymap.set("i", "<c-f>", "<RIGHT>")
-- vim.keymap.set({ "i" }, "<c-d>", "<DEL>")
-- vim.keymap.set({ "i", "n" }, "<c-z>", "<cmd>undo<CR>")
-- -- vim.keymap.set('n', '<C-Down>', '}', { noremap = true, silent = true })
-- -- vim.keymap.set('n', '<C-Up>', '{', { noremap = true, silent = true })
-- -- vim.keymap.set('n', '<CR>', 'yyp')
-- -- vim.keymap.set('n', '<S-CR>', 'dd O')
-- -- vim.keymap.set('i', '<S-CR>', '<ESC>dd O')
-- -- vim.keymap.set('i', '<C-CR>', '<ESC>}i')
-- -- vim.keymap.set('i', '<C-S-CR>', '<ESC>{i')
-- -- vim.keymap.set('n', '<C-S-CR>', '{i')
-- -- -- vim.keymap.set('n', '<BS>', '<LEFT><DEL>')
-- -- -- vim.keymap.set('v', '<BS>', 'x')
-- -- -- vim.keymap.set('n', '<S-BS>', '<C-i>')
-- -- vim.keymap.set('i', '<A-BS>', '<ESC>dd O')
-- -- vim.keymap.set('n', '<A-BS>', 'dd O')
-- -- vim.keymap.set('i', '<C-BS>', '<ESC><RIGHT>dbi')
-- -- vim.keymap.set('n', '<C-BS>', 'db')
-- -- vim.keymap.set('n', '<c-l>', 'J')
-- -- vim.keymap.set('i', '<c-l>', '<c-o>J')
-- -- vim.keymap.set('v', '<c-l>', '<c-o>J')
-- -- vim.keymap.set('n', '/', '<cmd>Telescope find_files<CR>')
-- -- vim.keymap.set('n', 'A', 'v')
-- -- vim.keymap.set('n', 'a', 'V')
-- -- -- vim.keymap.set('n', 'b', 'mA')
-- -- vim.keymap.set('n', 'ds', 'd/')
-- -- vim.keymap.set('n', 'e', '<cmd>Startify<CR>')
-- -- vim.keymap.set('n', '[f', '[z')
-- -- vim.keymap.set('n', ']f', ']z')
-- -- vim.keymap.set('n', 'G', 'Gzm')
-- -- vim.keymap.set('n', 'gg', 'ggzm')
-- -- vim.keymap.set('n', 'I', 'a')
-- -- vim.keymap.set('n', 'L', 'l')
-- -- vim.keymap.set('n', 'M', 'zM{zozz')
-- -- vim.keymap.set('v', 'M', 'zM{zozz')
-- -- vim.keymap.set('n', 'm', 'F')
-- -- vim.keymap.set('v', 'm', 'F')
-- -- vim.keymap.set('n', 'Q', ':qa<cr>')
-- -- vim.keymap.set('n', 'q', ':q<cr>')
-- -- vim.keymap.set('n', 'r', '/')
-- -- vim.keymap.set('n', 't', ''Azo')
-- -- vim.keymap.set('n', 'X', 'x')
-- -- vim.keymap.set('n', '`', '~<left>')
-- -- vim.keymap.set('v', '`', '~')
-- -- -- Save mappings
-- -- vim.keymap.set('n', '<c-s>', ':w<cr>')
-- -- vim.keymap.set('i', '<c-s>', '<ESC>:w<CR>a<ESC><RIGHT>')
-- -- vim.keymap.set('v', '<c-s>', '<ESC>:w<CR>a<ESC><RIGHT>')
-- -- -- Tab management
-- -- vim.keymap.set('n', '<c-t>', ':tabnew<CR>')
-- -- -- Emacs-like editing
-- -- vim.keymap.set('n', '<a-d>', '<c-o>dw')
-- -- vim.keymap.set('i', '<a-d>', '<c-o>dw')
-- -- vim.keymap.set('v', '<a-d>', '<c-o>dw')
-- -- vim.keymap.set('n', '<c-d>', 'x')
-- -- vim.keymap.set('i', '<c-d>', '<del>')
-- -- vim.keymap.set('v', '<c-d>', '<del>')
-- -- vim.keymap.set('c', '<c-d>', '<del>')
-- -- Other
-- -- vim.keymap.set('n', '<c-u>', 'dw')
-- -- Emacs-like movements
-- -- vim.keymap.set('n', '<c-a>', '^')
-- -- vim.keymap.set('i', '<c-a>', '<esc>^i')
-- -- vim.keymap.set('c', '<c-a>', '<home>')
-- -- vim.keymap.set('v', '<c-a>', '^')
-- -- vim.keymap.set('n', '<c-b>', '<left>')
-- -- vim.keymap.set('i', '<c-b>', '<left>')
-- -- vim.keymap.set('c', '<c-b>', '<left>')
-- -- vim.keymap.set('v', '<c-b>', '<left>')
-- -- vim.keymap.set('n', '<a-b>', 'b')
-- -- vim.keymap.set('n', '<c-e>', '<esc>$<esc>')
-- -- vim.keymap.set('i', '<c-e>', '<c-o>A')
-- -- vim.keymap.set('c', '<c-e>', '<c-o>A')
-- -- vim.keymap.set('v', '<c-e>', '$')
-- -- vim.keymap.set('n', '<c-f>', '<right>')
-- -- vim.keymap.set('i', '<c-f>', '<right>')
-- -- vim.keymap.set('c', '<c-f>', '<right>')
-- -- vim.keymap.set('v', '<c-f>', '<right>')
-- -- vim.keymap.set('n', '<c-g>', 'a<c-r>'<ESC>')
-- -- vim.keymap.set('i', '<c-g>', 'a<c-r>'<ESC>')
-- -- vim.keymap.set('c', '<c-g>', 'a<c-r>'<ESC>')
-- -- vim.keymap.set('v', '<c-g>', 'a<c-r>'<ESC>')
-- -- vim.keymap.set('n', '<c-n>', '<down>')
-- -- vim.keymap.set('i', '<c-n>', '<down>')
-- -- vim.keymap.set('c', '<c-n>', '<down>')
-- -- vim.keymap.set('v', '<c-n>', '<down>')
-- -- vim.keymap.set('n', '<c-p>', '<up>')
-- -- vim.keymap.set('i', '<c-p>', '<up>')
-- -- vim.keymap.set('c', '<c-p>', '<up>')
-- -- vim.keymap.set('v', '<c-p>', '<up>')
-- -- Copy and paste with control
-- -- vim.keymap.set('n', '<c-c>', 'yy')
-- -- vim.keymap.set('i', '<c-c>', '<esc>yy<right>i')
-- -- vim.keymap.set('v', '<c-c>', 'y')
-- -- vim.keymap.set('n', '<c-v>', '<left>p')
-- -- vim.keymap.set('i', '<c-v>', '<c-o>p')
-- -- vim.keymap.set('v', '<c-v>', '<c-o>p')
-- -- Undo and redo
-- vim.keymap.set("n", "<c-z>", "u")
-- vim.keymap.set("i", "<c-z>", "<c-o>u")
-- vim.keymap.set("v", "<c-z>", "<c-o>u")
-- -- Old
-- -- vim.api.nvim_set_keymap('n', '<S-CR>', '<C-u>', { silent = true })
-- -- vim.api.nvim_set_keymap('n', '<C-CR>', '<C-u>', { silent = true })
-- -- vim.api.nvim_set_keymap('n', '<BS>', '<LEFT><DEL>', { silent = true })
-- -- vim.api.nvim_set_keymap('v', '<BS>', 'x', { silent = true })
-- -- vim.api.nvim_set_keymap('n', '<S-BS>', '<C-i>', { silent = true })
-- -- vim.api.nvim_set_keymap('i', '<A-BS>', '<ESC><Right>d^i', { silent = true })
-- --- }}}
-- -- vim:foldmethod=marker:foldlevel=1
