#!/usr/local/bin/python3

import subprocess
import os
import sys
import inspect


class Project:
    def __init__(self, category, name):
        self.category = category
        self.name = name
        super().__init__()


def git_ls_files():
    try:
        # Run git ls-files in root directory
        shell_output = subprocess.check_output('git ls-files', shell=True).decode("utf-8").split(
            '\n')
        # Delete the last item because it is a blank new line
        del shell_output[-1]
        return shell_output
    except subprocess.CalledProcessError:
        pass


def format_as_md_list(projects):
    final_str = ''
    used_categories = []
    writing = False
    for project in projects:
        if writing:
            final_str += '  ' + project.name + '\n'
        if project.category not in used_categories:
            final_str += '* [{0}](https://github.com/nbassfish/Portfolio/tree/master/{0}\n'.format(project.category)
            final_str += '  - [{0}](https://github.com/nbassfish/{0}\n'.format(project.name)
            used_categories.append(project.category)
            writing = True
    return final_str


def write_to_readme(text):
    readme_str = '# Portfolio by Nate Bass\nThis page is automatically generated by the directory structure of this repository. (See [pre-commit.py](https://github.com/nbassfish/git-hooks/blob/master/py/pre-commit.py))\n## Projects\n'
    readme_str += text
    try:
        # Todo: Replace after "## Projects", probably using sed
        subprocess.check_output('echo "{0}" > README.md'.format(readme_str), shell=True)
    except subprocess.CalledProcessError:
        pass


##############################################################################
#                                                                            #
#  Append all projects in the repository to a list at the end of the README  #
#                                                                            #
##############################################################################
projects = []

# WTF: I have to unset GIT_DIR to make shell commands run in the root of the repository
subprocess.check_output('unset GIT_DIR', shell=True)

for file in git_ls_files():
    parts_file_path = file.split('/')
    # Files at the root directory are not projects
    if len(parts_file_path) > 1:
        # If the name contains a . it is a file and not a project
        if "." not in parts_file_path[1]:
            projects.append(Project(parts_file_path[0], parts_file_path[1]))
write_to_readme(format_as_md_list(projects))

# Re-add the file so that the generated README will be committed
subprocess.check_output('git add README.md', shell=True)
