local add, now, later = MiniDeps.add, MiniDeps.now, MiniDeps.later
now(function()
	add({ source = "mhinz/vim-startify" })
end)
now(function()
	add({ source = "vague2k/vague.nvim" })
	vim.cmd.colorscheme("vague")
	-- add({ source = 'folke/tokyonight.nvim' })
	-- vim.cmd('colorscheme tokyonight')
end)
later(function()
	add({ source = "nvim-focus/focus.nvim" })
	require("focus").setup()
end)
later(function()
	add({ source = "folke/zen-mode.nvim" })
end)
later(function()
	add({ source = "pocco81/true-zen.nvim" })
end)
later(function()
	add({ source = "junegunn/limelight.vim" })
end)
later(function()
	add({ source = "github/copilot.vim" })
end)
later(function()
	add({ source = "ggandor/leap.nvim" })
	-- require('leap').create_default_mappings()
	vim.keymap.set({ "n", "x", "o" }, "s", "<plug>(leap-forward)")
	vim.keymap.set({ "n", "x", "o" }, "S", "<plug>(leap-backward)")
	vim.keymap.set({ "n", "x", "o" }, "gs", "<plug>(leap-from-window)")
	vim.keymap.set({ "n", "x", "o" }, "gS", "<plug>(leap)")
end)
later(function()
	add({ source = "wakatime/vim-wakatime" })
end)
-- add({ source = 'neovim/nvim-lspconfig' })
-- vim.lsp.enable({'lua_ls'})
-- require('lspconfig').lua_ls.setup({
-- your config here
-- })
