--- Dump one colour scheme's resolved highlight groups as JSON.
---
--- The Color Themes page previews what Neovim actually renders rather than the
--- hex values written in each file. For the five mini.hues schemes those differ:
--- `make_palette()` treats the declared foreground as a *reference* and adjusts
--- it, so `miniwinter`'s `#cfd4e2` comes out as `#d8d4cd` on screen.
---
--- This cannot run during the site build — GitHub Actions has no Neovim, and no
--- mini.nvim to compute the palettes with — so its output is committed at
--- `documentation/src/data/theme-highlights.json` and regenerated by hand when a
--- scheme changes.
---
--- One scheme per process, on purpose: `mini.hues.setup()` installs a
--- `ColorScheme` autocommand that reapplies its own configuration, so looping
--- over every scheme in one session would let a later one be contaminated by an
--- earlier one's setup.
---
--- Usage, from the repository root:
---
---     for scheme in miniautumn minigrey minispring minisummer miniwinter \
---                   neovim_colors nordstone; do
---       for bg in dark light; do
---         QDTB_SCHEME=$scheme QDTB_BG=$bg QDTB_OUT=/tmp/$scheme.$bg.json \
---         QDTB_CONFIG=$PWD/QDtb QDTB_PACK=~/.local/share/nvim/site/pack/core/opt \
---           nvim --headless -u NONE -i NONE \
---             -c "luafile documentation/scripts/dump-theme-highlights.lua" -c "qa!"
---       done
---     done
---
--- Then merge the files into one object keyed by scheme, then by background.
--- @module "scripts.dump-theme-highlights"

local config = vim.env.QDTB_CONFIG or vim.fn.getcwd() .. "/QDtb"
local pack = vim.env.QDTB_PACK or (vim.fn.stdpath("data") .. "/site/pack/core/opt")
vim.opt.runtimepath:prepend(config)
vim.opt.runtimepath:prepend(pack .. "/mini.nvim")
vim.o.termguicolors = true

local scheme = assert(vim.env.QDTB_SCHEME, "set QDTB_SCHEME")
local background = vim.env.QDTB_BG or "dark"
local out_path = assert(vim.env.QDTB_OUT, "set QDTB_OUT")

--- The groups the preview draws with. Anything not listed is simply not shown.
local groups = {
	"Normal",
	"NormalFloat",
	"CursorLine",
	"Visual",
	"Comment",
	"Constant",
	"String",
	"Function",
	"Identifier",
	"Keyword",
	"Statement",
	"Type",
	"Special",
	"LineNr",
	"CursorLineNr",
	"Search",
	"IncSearch",
	"MatchParen",
	"Title",
	"Operator",
	"Number",
	"Boolean",
	"Pmenu",
	"PmenuSel",
	"StatusLine",
	"ColorColumn",
	"Folded",
	"DiffAdd",
	"DiffChange",
	"DiffDelete",
	"DiagnosticError",
	"DiagnosticWarn",
	"DiagnosticInfo",
	"DiagnosticHint",
	"@keyword",
	"@function",
	"@variable",
	"@string",
	"@comment",
	"@type",
	"@punctuation.delimiter",
	"@keyword.return",
	"@constant",
	"@field",
}

--- @param n integer|nil A packed 24-bit colour from nvim_get_hl.
--- @return string|nil hex `#rrggbb`, or nil when the group sets no such colour.
local function hex(n)
	return n and string.format("#%06x", n) or nil
end

--- Resolve a highlight group through its links.
--- `link = false` asks for the group's own definition, so a linked group has to
--- be followed by hand to report the colour it actually renders with.
--- @param name string Highlight group name.
--- @return table|nil
local function resolve(name)
	local ok, hl = pcall(vim.api.nvim_get_hl, 0, { name = name, link = false })
	if not ok then
		return nil
	end
	local followed = 0
	while hl and hl.link and followed < 10 do
		local ok_link, linked = pcall(vim.api.nvim_get_hl, 0, { name = hl.link, link = false })
		if not ok_link then
			break
		end
		hl, followed = linked, followed + 1
	end
	return hl
end

vim.o.background = background
local applied, err = pcall(vim.cmd.colorscheme, scheme)

local result
if not applied then
	result = { error = tostring(err) }
else
	result = { background = vim.o.background, colors_name = vim.g.colors_name }
	for _, group in ipairs(groups) do
		local hl = resolve(group)
		if hl and next(hl) ~= nil then
			result[group] = {
				fg = hex(hl.fg),
				bg = hex(hl.bg),
				bold = hl.bold or nil,
				italic = hl.italic or nil,
				reverse = hl.reverse or nil,
				underline = hl.underline or nil,
			}
		end
	end
end

local file = assert(io.open(out_path, "w"))
file:write(vim.json.encode(result))
file:close()
