-- ↓ -------- Learn -------- ↓
-- ↑ ----------------------- ↑
-- Leader Mappings {{{
vim.g.mapleader = " "
vim.keymap.set("n", "<leader>a", "<cmd>silent !npx prettier --write % &<CR>", { silent = true })
vim.keymap.set("n", "<leader>c", "<cmd>lua MiniPick.builtin.cli()<CR>")
vim.keymap.set("n", "<leader>d", "<cmd>lua MiniPick.builtin.grep_live()<CR>")
vim.keymap.set("n", "<leader>e", "<cmd>lua MiniPick.builtin.grep()<CR>")
vim.keymap.set("n", "<leader>f", "<cmd>lua MiniPick.builtin.files()<CR>")
vim.keymap.set("n", "<leader>g", "<cmd>set wrap<cr><cmd>Goyo<cr>")
vim.keymap.set("n", "<leader>h", "<cmd>lua MiniPick.builtin.help()<CR>")
vim.keymap.set("n", "<leader>i", "<cmd>Limelight!!<cr>", { silent = true })
vim.keymap.set("n", "<leader>J", "<cmd><c-p><cr>")
vim.keymap.set("n", "<leader>j", "<cmd><c-p>")
vim.keymap.set("n", "<leader>K", "/<c-f>")
vim.keymap.set("n", "<leader>k", "/<up>")
vim.keymap.set("n", "<leader>l", "<cmd>cw<cr>")
vim.keymap.set("n", "<leader>m", "=ip")
vim.keymap.set("n", "<leader>n", "<cmd>set wrap<cr><cmd>Goyo<cr>")
vim.keymap.set("n", "<leader>o", "<cmd>set nowrap<cr><cmd>Goyo<cr>", { silent = true })
vim.keymap.set("n", "<leader>p", "<cmd>lua MiniExtra.pickers.colorschemes()<CR>")
vim.keymap.set("n", "<leader>q", "<cmd>lua MiniPick.builtin.help()<CR>")
vim.keymap.set("n", "<leader>r", "qr")
vim.keymap.set("n", "<leader>s", "<cmd>%s//<left>")
vim.keymap.set("n", "<leader>t", '<cmd>lua MiniSessions.read("0")<CR>')
vim.keymap.set("n", "<leader>u", "<cmd>lua MiniPick.builtin.buffers()<CR>")
vim.keymap.set("n", "<leader>v", "<cmd>TZNarrow<CR>")
vim.keymap.set("n", "<leader>w", require("plugins.QDtb.lua_format").format, { desc = "Run Formatting" })
vim.keymap.set("n", "<leader>x", "w")
vim.keymap.set("n", "<leader>y", "q")
vim.keymap.set("n", "<leader>.", ":cd %:p:h<CR>", { silent = true })
-- }}}
-- Mode mappings {{{

-- vim.keymap.set('i', 'kj', '<ESC>')
-- vim.keymap.set('i', 'jk', '<ESC>')
vim.keymap.set("n", "<S-CR>", "yyP")
vim.keymap.set("n", "<S-CR>", "yyP")
vim.keymap.set("v", "<S-CR>", "yP")
vim.keymap.set("n", "<CR>", "yyp")
vim.keymap.set("v", "<CR>", "yp")
vim.keymap.set("n", "/", "<cmd>lua MiniPick.builtin.files()<CR>")
vim.keymap.set("n", ",", "}")
vim.keymap.set("n", "a", "V")
vim.keymap.set("n", "E", "<cmd>cd %:p:h<CR>")
vim.keymap.set("n", "e", "<cmd>Startify<CR>")
vim.keymap.set("n", "gg", "ggzM")
vim.keymap.set("n", "I", "a")
-- vim.keymap.set'n', 'J', '')
-- vim.keymap.set('n', 'K', '')
-- vim.keymap.set('n', 'Q', '<cmd>lua MiniSessions.write(0)<CR>')
-- require('mini.splitjoin').setup({ mappings = { toggle = 'm' } })
-- vim.keymap.set('n', 'q', '<cmd>q<CR>')
vim.keymap.set("n", "R", "q")
vim.keymap.set("n", "r", "/")
-- vim.keymap.set('n', 'T', 'A<c-r>+<ESC>')
-- vim.keymap.set('n', 'T', '')
-- vim.keymap.set('n', 't', '@r')
-- vim.keymap.set('n', 't', '<cmd>bd<CR>')
vim.keymap.set("n", "U", "<cmd>cd %:p:h<CR>")
vim.keymap.set("n", "V", "A")
vim.keymap.set("n", "X", "x")
vim.keymap.set("n", ";", ";")
-- vim.keymap.set('n', ';', 'q:')
vim.keymap.set("n", "-", function()
	require("mini.files").open()
end, { noremap = true, silent = true, desc = "Open MiniFiles" })
-- vim.keymap.set('n', 'E', function()
-- 	local directory = '~/Source/Repos/be-gccpilot03-py/frontend'
-- 	vim.cmd('silent! Explore ' .. vim.fn.escape(directory, ' '))
-- 	vim.cmd('cd ' .. vim.fn.escape(directory, ' '))
-- end)
vim.keymap.set("n", "h", function()
	MiniFiles.open(vim.api.nvim_buf_get_name(0))
end, { noremap = true, silent = true, desc = "Open MiniFiles" })
vim.keymap.set("n", "<X2Mouse>", "<c-i>")
vim.keymap.set("n", "<X1Mouse>", "<c-o>")
vim.keymap.set("n", "<c-a>", "|")
vim.keymap.set("i", "<c-a>", "<ESC>|i")
vim.keymap.set("i", "<c-b>", "<LEFT>")
vim.keymap.set("i", "<c-e>", "<ESC>A")
vim.keymap.set("i", "<c-f>", "<RIGHT>")
vim.keymap.set({ "i" }, "<c-d>", "<DEL>")
vim.keymap.set({ "i", "n" }, "<c-z>", "<cmd>undo<CR>")
-- vim.keymap.set('n', '<C-Down>', '}', { noremap = true, silent = true })
-- vim.keymap.set('n', '<C-Up>', '{', { noremap = true, silent = true })
-- vim.keymap.set('n', '<CR>', 'yyp')
-- vim.keymap.set('n', '<S-CR>', 'dd O')
-- vim.keymap.set('i', '<S-CR>', '<ESC>dd O')
-- vim.keymap.set('i', '<C-CR>', '<ESC>}i')
-- vim.keymap.set('i', '<C-S-CR>', '<ESC>{i')
-- vim.keymap.set('n', '<C-S-CR>', '{i')
-- -- vim.keymap.set('n', '<BS>', '<LEFT><DEL>')
-- -- vim.keymap.set('v', '<BS>', 'x')
-- -- vim.keymap.set('n', '<S-BS>', '<C-i>')
-- vim.keymap.set('i', '<A-BS>', '<ESC>dd O')
-- vim.keymap.set('n', '<A-BS>', 'dd O')
-- vim.keymap.set('i', '<C-BS>', '<ESC><RIGHT>dbi')
-- vim.keymap.set('n', '<C-BS>', 'db')
-- vim.keymap.set('n', '<c-l>', 'J')
-- vim.keymap.set('i', '<c-l>', '<c-o>J')
-- vim.keymap.set('v', '<c-l>', '<c-o>J')
-- vim.keymap.set('n', '/', '<cmd>Telescope find_files<CR>')
-- vim.keymap.set('n', 'A', 'v')
-- vim.keymap.set('n', 'a', 'V')
-- -- vim.keymap.set('n', 'b', 'mA')
-- vim.keymap.set('n', 'ds', 'd/')
-- vim.keymap.set('n', 'e', '<cmd>Startify<CR>')
-- vim.keymap.set('n', '[f', '[z')
-- vim.keymap.set('n', ']f', ']z')
-- vim.keymap.set('n', 'G', 'Gzm')
-- vim.keymap.set('n', 'gg', 'ggzm')
-- vim.keymap.set('n', 'I', 'a')
-- vim.keymap.set('n', 'L', 'l')
-- vim.keymap.set('n', 'M', 'zM{zozz')
-- vim.keymap.set('v', 'M', 'zM{zozz')
-- vim.keymap.set('n', 'm', 'F')
-- vim.keymap.set('v', 'm', 'F')
-- vim.keymap.set('n', 'Q', ':qa<cr>')
-- vim.keymap.set('n', 'q', ':q<cr>')
-- vim.keymap.set('n', 'r', '/')
-- vim.keymap.set('n', 't', ''Azo')
-- vim.keymap.set('n', 'X', 'x')
-- vim.keymap.set('n', '`', '~<left>')
-- vim.keymap.set('v', '`', '~')
-- -- Save mappings
-- vim.keymap.set('n', '<c-s>', ':w<cr>')
-- vim.keymap.set('i', '<c-s>', '<ESC>:w<CR>a<ESC><RIGHT>')
-- vim.keymap.set('v', '<c-s>', '<ESC>:w<CR>a<ESC><RIGHT>')
-- -- Tab management
-- vim.keymap.set('n', '<c-t>', ':tabnew<CR>')
-- -- Emacs-like editing
-- vim.keymap.set('n', '<a-d>', '<c-o>dw')
-- vim.keymap.set('i', '<a-d>', '<c-o>dw')
-- vim.keymap.set('v', '<a-d>', '<c-o>dw')
-- vim.keymap.set('n', '<c-d>', 'x')
-- vim.keymap.set('i', '<c-d>', '<del>')
-- vim.keymap.set('v', '<c-d>', '<del>')
-- vim.keymap.set('c', '<c-d>', '<del>')
-- Other
-- vim.keymap.set('n', '<c-u>', 'dw')
-- Emacs-like movements
-- vim.keymap.set('n', '<c-a>', '^')
-- vim.keymap.set('i', '<c-a>', '<esc>^i')
-- vim.keymap.set('c', '<c-a>', '<home>')
-- vim.keymap.set('v', '<c-a>', '^')
-- vim.keymap.set('n', '<c-b>', '<left>')
-- vim.keymap.set('i', '<c-b>', '<left>')
-- vim.keymap.set('c', '<c-b>', '<left>')
-- vim.keymap.set('v', '<c-b>', '<left>')
-- vim.keymap.set('n', '<a-b>', 'b')
-- vim.keymap.set('n', '<c-e>', '<esc>$<esc>')
-- vim.keymap.set('i', '<c-e>', '<c-o>A')
-- vim.keymap.set('c', '<c-e>', '<c-o>A')
-- vim.keymap.set('v', '<c-e>', '$')
-- vim.keymap.set('n', '<c-f>', '<right>')
-- vim.keymap.set('i', '<c-f>', '<right>')
-- vim.keymap.set('c', '<c-f>', '<right>')
-- vim.keymap.set('v', '<c-f>', '<right>')
-- vim.keymap.set('n', '<c-g>', 'a<c-r>'<ESC>')
-- vim.keymap.set('i', '<c-g>', 'a<c-r>'<ESC>')
-- vim.keymap.set('c', '<c-g>', 'a<c-r>'<ESC>')
-- vim.keymap.set('v', '<c-g>', 'a<c-r>'<ESC>')
-- vim.keymap.set('n', '<c-n>', '<down>')
-- vim.keymap.set('i', '<c-n>', '<down>')
-- vim.keymap.set('c', '<c-n>', '<down>')
-- vim.keymap.set('v', '<c-n>', '<down>')
-- vim.keymap.set('n', '<c-p>', '<up>')
-- vim.keymap.set('i', '<c-p>', '<up>')
-- vim.keymap.set('c', '<c-p>', '<up>')
-- vim.keymap.set('v', '<c-p>', '<up>')
-- Copy and paste with control
-- vim.keymap.set('n', '<c-c>', 'yy')
-- vim.keymap.set('i', '<c-c>', '<esc>yy<right>i')
-- vim.keymap.set('v', '<c-c>', 'y')
-- vim.keymap.set('n', '<c-v>', '<left>p')
-- vim.keymap.set('i', '<c-v>', '<c-o>p')
-- vim.keymap.set('v', '<c-v>', '<c-o>p')
-- Undo and redo
vim.keymap.set("n", "<c-z>", "u")
vim.keymap.set("i", "<c-z>", "<c-o>u")
vim.keymap.set("v", "<c-z>", "<c-o>u")
-- Old
-- vim.api.nvim_set_keymap('n', '<S-CR>', '<C-u>', { silent = true })
-- vim.api.nvim_set_keymap('n', '<C-CR>', '<C-u>', { silent = true })
-- vim.api.nvim_set_keymap('n', '<BS>', '<LEFT><DEL>', { silent = true })
-- vim.api.nvim_set_keymap('v', '<BS>', 'x', { silent = true })
-- vim.api.nvim_set_keymap('n', '<S-BS>', '<C-i>', { silent = true })
-- vim.api.nvim_set_keymap('i', '<A-BS>', '<ESC><Right>d^i', { silent = true })
--- }}}
-- vim:foldmethod=marker:foldlevel=1
