vim.opt.guifont = "Cascadia Code:h11.5"
vim.o.linespace = 4
vim.o.cmdheight = 0
vim.o.laststatus = 0
vim.opt.colorcolumn = "+1" -- Highlight one column past 'textwidth'
vim.o.title = true
vim.o.confirm = true
vim.o.number = false
vim.o.cursorline = false
vim.o.guicursor = "n-v-c-sm:hor10,i-ci-ve:ver25,r-cr-o:block"
vim.o.winborder = "rounded"
vim.opt.tabstop = 4 -- Number of visual spaces per TAB
vim.opt.softtabstop = 4 -- Number of spaces inserted when pressing TAB
vim.opt.shiftwidth = 4 -- Number of spaces used for autoindent
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.undofile = true
vim.opt.swapfile = false
vim.opt.formatoptions:remove({ "c", "r", "o" })
vim.opt.signcolumn = "yes"
-- vim.o.termguicolors = true
-- vim.opt.foldmethod = 'marker'
-- vim.opt.foldlevel = 1
