;;; .user-lisp-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from my-commands.el

(autoload 'my-command-palette "my-commands"
"Interactively select and execute an Emacs command." t)


;;; Generated autoloads from my-dev.el

(autoload 'my-dev-server "my-dev"
"Run the project's development server." t)


;;; Generated autoloads from my-editing.el

(autoload 'my-duplicate-line "my-editing"
"Duplicate the current line." t)
(autoload 'my-open-init-file "my-editing"
"Open the user's Emacs configuration." t)


;;; Generated autoloads from my-git.el

(autoload 'my-git-status "my-git"
"Open Git status for the current project." t)


;;; Generated autoloads from my-project.el

(autoload 'my-project-find-config "my-project"
"Open the project configuration file." t)
(autoload 'my-project-shell "my-project"
"Open a shell at the current project root." t)


;;; Generated autoloads from my-test.el

(autoload 'my-test "my-test"
"Test user-lisp." t)


;;; Generated autoloads from my-treesit.el

(autoload 'my-enable-treesit "my-treesit"
"Prefer Tree-sitter major modes when available.")

;;; End of scraped data

(provide '.user-lisp-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; .user-lisp-autoloads.el ends here
