import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  configSidebar: [
    {
      type: "doc",
      id: "index",
      label: "Introduction",
    },
    {
      type: "doc",
      id: "config/init",
      label: "Init",
    },
    {
      type: "doc",
      id: "config/options",
      label: "Options",
    },
    {
      type: "doc",
      id: "config/keymaps",
      label: "Keymaps",
    },
    {
      type: "category",
      label: "Plugins",
      items: [
        {
          type: "autogenerated",
          dirName: "plugins",
        },
      ],
    },
    {
      type: "category",
      label: "Color Schemes",
      items: [
        {
          type: "autogenerated",
          dirName: "colors",
        },
      ],
    },
    {
      type: "doc",
      id: "modules",
      label: "Index",
    },
  ],
  powershellSidebar: [
    {
      type: "autogenerated",
      dirName: "powershell",
    },
  ],
  fishSidebar: [
    {
      type: "autogenerated",
      dirName: "fish",
    },
  ],
  docusaurusSidebar: [
    {
      type: "autogenerated",
      dirName: "docusaurus",
    },
  ],
};

export default sidebars;
