import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Hand-written prose is listed explicitly; the Lua reference is autogenerated
 * from `docs/reference`, which `nvim-docusaurus` rewrites on every build.
 *
 * The reference category has no `link` on purpose. Its own overview page sits
 * inside `docs/reference` as `index.md`, so giving the category a doc link as
 * well would list that page twice.
 */
const sidebars: SidebarsConfig = {
  configSidebar: [
    {
      type: "doc",
      id: "index",
      label: "Introduction",
    },
    {
      type: "category",
      label: "Lua Reference",
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "reference",
        },
      ],
    },
  ],
  powershellSidebar: [
    {
      type: "autogenerated",
      dirName: "powershell",
    },
  ],
  fishSidebar: [
    {
      type: "autogenerated",
      dirName: "fish",
    },
  ],
  docusaurusSidebar: [
    {
      type: "autogenerated",
      dirName: "docusaurus",
    },
  ],
};

export default sidebars;
